CREATE TABLE db_STUaffair.new_student (
  new_stuid INT NOT NULL AUTO_INCREMENT,
  student_id INT(20) NOT NULL,
  academic VARCHAR(45) NOT NULL,
  name VARCHAR(45) NOT NULL,
  nrc_no VARCHAR(20) NOT NULL,
  photo VARCHAR(45) NOT NULL,
  gender CHAR(10) NOT NULL,
  birthday DATE NOT NULL,
  religion VARCHAR(45) NOT NULL,
  nationality VARCHAR(45) NOT NULL,
  address VARCHAR(128) NOT NULL,
  phone_no INT(12) NOT NULL,
  father_name VARCHAR(45) NOT NULL,
  f_nrc VARCHAR(45) NOT NULL,
  f_occupation VARCHAR(128) NULL,
  f_religion VARCHAR(45) NULL,
  f_nationality VARCHAR(45) NOT NULL,
  mother_name VARCHAR(45) NOT NULL,
  m_nrc VARCHAR(45) NOT NULL,
  m_occupation VARCHAR(128) NULL,
  m_religion VARCHAR(45) NULL,
  m_nationality VARCHAR(45) NOT NULL,
  high_school_name VARCHAR(128) NOT NULL,
  high_school_success_year DATE NOT NULL,
  high_school_roll_no VARCHAR(10) NOT NULL,
  examiner_dep VARCHAR(45) NOT NULL,
  high_school_subject_mark VARCHAR(45) NOT NULL,
  high_school_total_mark INT(10) NOT NULL,
  mat_cer VARCHAR(45) NOT NULL,
  health_rec VARCHAR(45) NOT NULL,
  police_rec VARCHAR(45) NOT NULL,
  quarter_rec VARCHAR(45) NOT NULL,
  updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  inserted DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedby INT(11) NULL,
  insertedby INT(11) NULL,
  PRIMARY KEY (new_stuid),
  UNIQUE INDEX student_id_UNIQUE (student_id ASC));
