CREATE TABLE db_STUaffair.new_student (
  new_stuid INT NOT NULL AUTO_INCREMENT,
  student_id VARCHAR(20) NOT NULL,
  name VARCHAR(45) NOT NULL,
  nrc_no VARCHAR(20) NOT NULL,
  photo VARCHAR(45) NOT NULL,
  gender CHAR(10) NOT NULL,
  birthday DATE NOT NULL,
  religion VARCHAR(45) NULL,
  nationality VARCHAR(45) NOT NULL,
  address VARCHAR(128) NOT NULL,
  phone_no INT NOT NULL,
  father_name VARCHAR(45) NOT NULL,
  f_nrc VARCHAR(45) NOT NULL,
  f_occupation VARCHAR(128) NULL,
  f_religion VARCHAR(45) NULL,
  f_nationality VARCHAR(45) NOT NULL,
  mother_name VARCHAR(45) NOT NULL,
  m_nrc VARCHAR(45) NOT NULL,
  m_occupation VARCHAR(45) NULL,
  m_religion VARCHAR(45) NULL,
  m_nationality VARCHAR(45) NOT NULL,
  high_school_name VARCHAR(45) NOT NULL,
  high_school_success_year DATE NOT NULL,
  high_school_roll_no VARCHAR(10) NOT NULL,
  examiner_dep VARCHAR(128) NOT NULL,
  high_school_subject_mark VARCHAR(45) NOT NULL,
  high_school_total_mark VARCHAR(45) NOT NULL,
  health_rec VARCHAR(45) NOT NULL,
  police_rec VARCHAR(45) NOT NULL,
  updated DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  inserted DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (new_stuid),
  UNIQUE INDEX new_stuid_UNIQUE (new_stuid ASC));
