CREATE TABLE db_STUaffair.old_student (
  old_stuid INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  nrc_no VARCHAR(20) NOT NULL,
  s_year VARCHAR(20) NOT NULL,
  photo VARCHAR(45) NOT NULL,
  gender CHAR(1) NOT NULL,
  birthday DATE NOT NULL,
  religion VARCHAR(45) NULL,
  nationality VARCHAR(45) NOT NULL,
  address VARCHAR(128) NOT NULL,
  phone_no INT NOT NULL,
  father_name VARCHAR(45) NOT NULL,
  f_nrc VARCHAR(45) NOT NULL,
  f_occupation VARCHAR(128) NULL,
  f_religion VARCHAR(45) NULL,
  f_nationality VARCHAR(45) NOT NULL,
  mother_name VARCHAR(45) NOT NULL,
  m_nrc VARCHAR(45) NOT NULL,
  m_occupation VARCHAR(45) NULL,
  m_religion VARCHAR(45) NULL,
  m_nationality VARCHAR(45) NOT NULL,
  high_school_success_year DATE NOT NULL,
  high_school_roll_no VARCHAR(10) NOT NULL,
  updated DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  inserted DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (old_stuid),
  UNIQUE INDEX old_stuid_UNIQUE (old_stuid ASC));
