CREATE TABLE db_STUaffair.subject (
  sub_id INT NOT NULL AUTO_INCREMENT,
  sub_name VARCHAR(45) NOT NULL,
  sub_code VARCHAR(45) NOT NULL,
  major VARCHAR(45) NOT NULL,
  s_year VARCHAR(45) NOT NULL,
  updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  inserted DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedby INT(11) NULL,
  insertedby INT(11) NULL,
  PRIMARY KEY (sub_id));
